export const Subjects = [
  { name: '발상과 시각화', kind: 'GI' },
  { name: '모바일프로그래밍', kind: 'GI' },
  { name: '3D그래픽디자인', kind: 'GI' },
  { name: '크리에이티브미디어프로그래밍', kind: 'GI' },
  { name: '3D어셋크리에이션', kind: 'GI' },
  { name: '게임의이해', kind: 'GI' },
  { name: '몰입형미디어프로그래밍', kind: 'GI' },
  { name: '게임엔진프로그래밍', kind: 'GI' },
  { name: '공간음향제작', kind: 'GI' },
  { name: '데이터베이스', kind: 'GI' },
  { name: 'VR스튜디오', kind: 'GI' },
  { name: '인디게임제작', kind: 'GI' },
  { name: '미디어소프트웨어엔지니어링', kind: 'GI' },
  { name: '시리어스게임분석', kind: 'GI' },
  { name: '비쥬얼커뮤니케이션디자인', kind: 'CD' },
];
