# main-cicd.yml
name: main

on:
  push:
    branches:
      - main # main branch에서 push event시 실행



jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Commit
        uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm dependencies
      uses: actions/cache@v2
      id: cache-dependencies
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

      # npm 설치
      - name: Install Dependencies
          run: npm install

      # 빌드
      - name: Build
          run: npm run build

      ## aws s3에 deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://fe-newmil-s3